#!/bin/sh

DEPLOY_DIR=~/shitwell
SERVER_DIR="$DEPLOY_DIR"/server
GIT_DIR="$DEPLOY_DIR"/raspo.git
CLIENT_DIR="$DEPLOY_DIR"/client

# actually get files from git into hdd
git --work-tree="$DEPLOY_DIR" --git-dir="$GIT_DIR" checkout -f

# files that have been changed since last commit
#changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

#check_run() {
#	echo "$changed_files" | grep --quiet "$1" && eval "$2"
#}

echo "Running server npm install"
cd "$SERVER_DIR"
#check_run server/package.json "npm prune && npm install"
echo "doned"

echo "running client npm install"
cd "$CLIENT_DIR"
#check_run client/package.json "npm prune && npm install"
echo "doned"

echo "running client build..."
cd "$CLIENT_DIR"
npm run build
echo "doned.."

touch "$SERVER_DIR"/index.js

#forever start index.js

echo "All done ;)"